# Data Paths
data:
  material_image_dir: "/dss/dsshome1/00/ge53gez2/01_Master_thesis/02_data_sets/14_FaMatMuc/03_Images/20250204_backup_annotation/Images_FaMatMuc_Original" # Change accordingly when we want to train a new model
  material_json_dir: "/dss/dsshome1/00/ge53gez2/01_Master_thesis/02_data_sets/14_FaMatMuc/03_Images/20250204_backup_annotation/Images_FaMatMuc_Original" # Change accordingly when we want to train a new model
  element_image_dir: "/dss/dsshome1/00/ge53gez2/01_Master_thesis/02_data_sets/e_Trims_JSON" # Change accordingly when we want to train a new model
  element_json_dir: "/dss/dsshome1/00/ge53gez2/01_Master_thesis/02_data_sets/e_Trims_JSON" # Change accordingly when we want to train a new model

# Output Paths
output:
  log_dir_base: "wattwert_only_mtl/runs/logs" # Does this path hold under any circumstances?
  model_save_path: "wattwert_only_mtl/data/trained_mtl_simult.pth" # Does this path hold under any circumstances?
  test_indices_path: "wattwert_only_mtl/runs/data_splits" # Does this path hold under any circumstances?

# Model Configuration
model:
  num_classes_elements: 10
  num_classes_materials: 8

# Training Hyperparameters
training:
  batch_size: 4
  num_workers: 2
  learning_rate: 7.277911691806096e-05
  weight_decay: 0.005639255190523905
  num_epochs: 30
  aux_weight: 0.4
  #task_weights: [0.5, 0.5]  # [element_weight, material_weight]

# Class Mappings
class_mappings:
  materials:
    stucco: 1
    brick: 2
    stone: 3
    concrete: 4
    glass: 5
    timber: 6
    other: 7
  elements:
    window: 1
    building: 2
    door: 3
    sky: 4
    pavement: 5
    vegetation: 6
    car: 7
    road: 8
    roof: 9